2020-12-23 15:24:14,339 - D:\ZYCami_00\Public\Caplictily.py[line:44] - ERROR: 错误：Message: An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s 5151523754573398 shell getprop ro.build.version.release' exited with code 1'; Stderr: 'error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.'; Code: '1'

2020-12-23 15:24:14,342 - D:\ZYCami_00\PO\Base_page.py[line:31] - ERROR: ('xpath', '//*[@content-desc="Editor"]/android.widget.ImageView')元素可见失效，错误：'NoneType' object has no attribute 'find_element'
2020-12-24 15:16:27,147 - D:\ZYCami_00\Public\Caplictily.py[line:44] - ERROR: 错误：HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016960E18688>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2020-12-24 15:16:27,149 - D:\ZYCami_00\PO\Base_page.py[line:31] - ERROR: ('xpath', '//*[@content-desc="Editor"]/android.widget.ImageView')元素可见失效，错误：'NoneType' object has no attribute 'find_element'
2020-12-24 15:16:53,128 - D:\ZYCami_00\Public\Caplictily.py[line:44] - ERROR: 错误：HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001508BDE85C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2020-12-24 15:16:53,130 - D:\ZYCami_00\PO\Base_page.py[line:31] - ERROR: ('xpath', '//*[@content-desc="Editor"]/android.widget.ImageView')元素可见失效，错误：'NoneType' object has no attribute 'find_element'
