2020-12-02 10:56:26,457 - D:\ZYCami_00\PO\Base_page.py[line:28] - ERROR: ('xpath', '//android.widget.FrameLayout[@content-desc="Me"]/android.widget.ImageView')元素可见失效，错误：Message: 

2020-12-02 10:57:26,230 - D:\ZYCami_00\PO\Base_page.py[line:28] - ERROR: ('xpath', '//android.widget.FrameLayout[@content-desc="Me"]/android.widget.ImageView')元素可见失效，错误：Message: 

2020-12-02 10:58:58,562 - D:\ZYCami_00\PO\Base_page.py[line:28] - ERROR: ('xpath', '//android.widget.FrameLayout[@content-desc="Me"]/android.widget.ImageView')元素可见失效，错误：Message: 

2020-12-02 10:59:41,873 - D:\ZYCami_00\PO\Base_page.py[line:28] - ERROR: ('xpath', '//android.widget.FrameLayout[@content-desc="Editor"]/android.widget.ImageView')元素可见失效，错误：Message: 

2020-12-02 16:26:22,492 - D:\ZYCami_00\Public\Caplictily.py[line:44] - ERROR: 错误：HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000184E6833D88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2020-12-02 16:27:04,075 - D:\ZYCami_00\Public\Caplictily.py[line:44] - ERROR: 错误：HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E641AE4C88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2020-12-02 16:29:08,593 - D:\ZYCami_00\Public\Caplictily.py[line:44] - ERROR: 错误：HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022582726A08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
